#!/usr/bin/env bash

VSCODE_EXTENSIONS_PATH="vscode_extensions.txt"
TERMINAL_DCONF_PATH="gnome_terminal_dconf.txt"

case "$1" in
  load)
    LOADING=true
    ;;
  dump)
    ;;
  *)
    echo "Argument required: load|dump"
    exit 1
    ;;
esac

vscode() {
  if [[ $LOADING ]]; then
    while read extension; do
      code --install-extension $extension --force
    done < $VSCODE_EXTENSIONS_PATH
  else
    code --list-extensions > $VSCODE_EXTENSIONS_PATH
  fi
}

terminal() {
  if [[ $LOADING ]]; then
    dconf load /org/gnome/terminal/ < $TERMINAL_DCONF_PATH
  else
    dconf dump /org/gnome/terminal/ > $TERMINAL_DCONF_PATH
  fi
}

vscode
terminal
