theme = "github_light_high_contrast"

[editor]
line-number = "relative"
auto-save = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"


[keys.normal]
C-s = ":w"
X = ["extend_line_up", "extend_to_line_bounds"]
