theme = "github_light_high_contrast"

[editor]
line-number = "relative"
auto-save = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
C-k = "toggle_comments"
X = ["extend_line_up", "extend_to_line_bounds"]
p = "paste_before"
C-v = ":clipboard-paste-before"
C-c = ":clipboard-yank"
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
C-S-right = "extend_next_word_end"
C-S-left = "extend_prev_word_start"
S-end = "extend_to_line_end"
S-home = "extend_to_line_start"

[keys.insert]
C-k = "toggle_comments"
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
C-S-right = "extend_next_word_end"
C-S-left = "extend_prev_word_start"
S-end = "extend_to_line_end"
S-home = "extend_to_line_start"

[keys.select]
C-k = "toggle_comments"
C-right = "extend_next_word_start"
C-left = "extend_prev_word_end"
S-right = "extend_char_right"
S-left = "extend_char_left"
C-S-right = "extend_next_word_end"
C-S-left = "extend_prev_word_start"
S-end = "extend_to_line_end"
S-home = "extend_to_line_start"
